### ISSUE TITLE
Example screen instead of application when building with build.phonegap.com 

### ISSUE THREAD

**Issue by qunabu** [phonegap-build/GAPlugin#80]
I'ce come accross weird issue. When building app with local phonegap everything seems to be fine. 
But when I'm deploying an app with build.phonegap.com service i see contents of com.adobe.plugins.GAPlugin/Example/index.html https://www.dropbox.com/s/husrnikd6wm82ge/Screenshot_2014-12-11-15-03-10.png?dl=0. 

It's likely that build.phonegap.com service is looking for a wring index.html file. 

This happends only for Android. 

My config.xml has 

<gap:plugin name="com.adobe.plugins.gaplugin" />

```
<feature name="GAPlugin" >
    <param name="android-package" value="com.adobe.plugins.GAPlugin"/>
</feature>
```

At the moment i have no idea how to fix this issue.

**Comment by dotNetkow** [comment]
Building for PhoneGap locally vs. using PhoneGap Build means that your config.xml file will look a bit different.  In this case, you should use:

```
<gap:plugin name="com.adobe.plugins.gaplugin" version="2.4.0" />
```

Hope that helps!
